version: '3.8'

services:
  frontend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.frontend
    container_name: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.backend
      target: production
    container_name: backend-app
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks:
  app-network:
    driver: bridge 