# Docker Compose для продакшен окружения

services:
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-username}/${FRONTEND_IMAGE:-fullstack-app-frontend}:${TAG:-latest}
    container_name: fullstack-app-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-username}/${BACKEND_IMAGE:-fullstack-app-backend}:${TAG:-latest}
    container_name: fullstack-app-backend
    restart: always
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge 