name: Frontend CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'apps/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'apps/frontend/package-lock.json'

    - name: Install dependencies
      run: |
        cd apps/frontend
        npm ci

    - name: Run linting
      run: |
        cd apps/frontend
        npm run lint

    - name: Build project
      run: |
        cd apps/frontend
        npm run build

    - name: Log in to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      if: github.event_name != 'pull_request'
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./infra/docker/Dockerfile.frontend
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/frontend:latest
          ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max 